### ISSUE TITLE
Compatibility with Pytorch 0.4

### ISSUE THREAD

**Issue by saba155** [qianguih/RSNet#5]
I am trying to run code using python 3.5 and I have pytorch 0.4.1 installed. I always end up getting error below:
Traceback (most recent call last):
  File "train.py", line 205, in <module>
    hidden_list = repackage_hidden(hidden_list)
  File "train.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "train.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/home/usr/.local/lib/python3.5/site-packages/torch/tensor.py", line 381, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

**Comment by BenjiDayan** [comment]
@SabaMehmood15 ,
I initially had the same error (on python 2.7, pytorch 0.4.1), the readme does say they tested on pytorch 0.3.0 and python 2.7. After downgrading pytorch it worked fine for me.

**Comment by hiram94** [comment]
@SabaMehmood15 
Just modify the code as **below**, there are somewhere else need to modify but I forget the specific position , so if you encounter other problems I can check for you..  Now I run it well using pytorch4.0 with python 3.6.4. However, **my problem** is that I failed to modify the code to get the same accuracy reported in the author paper. If anyone know how to solve the problem, please give me a hand.
#if type(h) == Variable:
    #    return Variable(h.data)
if isinstance(h, torch.Tensor):
       return h.detach()

**Comment by SmallHedgehog** [comment]
Modify 'type(h) == Variable' to 'type(h) == torch.Tensor'

#-- helper func for rnn units
def repackage_hidden(h):
    """Wraps hidden states in new Variables, to detach them from their history."""
    # if type(h) == Variable:
    #    return Variable(h.data)
    if type(h) == torch.Tensor:
    	return Variable(h.data)
    else:
        return tuple(repackage_hidden(v) for v in h)
